# Generated by Django 4.1.1 on 2022-09-13 21:05

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_expense_transfertomake_expensecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='paid_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 23, 5, 6, 258445), null=True),
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('balance_impact', models.FloatField(null=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.expense')),
                ('group_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='groups.groupuser')),
            ],
        ),
    ]
